#!/usr/bin/env python3
"""Generate research report from experiment data. Usage: python3 generate_report.py"""
import json, glob, os
from datetime import datetime

def main():
    exps = []
    for f in sorted(glob.glob("experiments/exp_*.json")):
        try:
            with open(f) as fh: exps.append(json.load(fh))
        except: pass

    succeeded = [e for e in exps if e.get("status") == "success" and e.get("metrics",{}).get("val_bpb")]
    if not succeeded:
        print("No successful experiments yet.")
        return

    succeeded.sort(key=lambda e: e["metrics"]["val_bpb"])
    best = succeeded[0]
    baseline = 1.2244

    # Build improvement timeline
    timeline = []
    best_so_far = 999
    for e in exps:
        b = e.get("metrics",{}).get("val_bpb")
        if b and e.get("status") == "success" and b < best_so_far:
            best_so_far = b
            timeline.append(e)

    os.makedirs("reports", exist_ok=True)

    report = f"""# Parameter Golf: Activation × Quantization Ablation Study
## Research Report — {datetime.now().strftime('%Y-%m-%d')}

### Summary

**{len(exps)} experiments** over {sum(e.get('duration_seconds',0) for e in exps)/3600:.1f} GPU-hours.
Best val_bpb: **{best['metrics']['val_bpb']:.4f}** ({(baseline - best['metrics']['val_bpb'])/baseline*100:.1f}% improvement over 1.2244 baseline).

| Metric | Value |
|--------|-------|
| Total experiments | {len(exps)} |
| Successful | {len(succeeded)} ({len(succeeded)/max(len(exps),1)*100:.0f}%) |
| Failed | {len(exps) - len(succeeded)} |
| Best val_bpb | **{best['metrics']['val_bpb']:.4f}** |
| Best experiment | {best['name']} |
| GPU time | {sum(e.get('duration_seconds',0) for e in exps)/3600:.1f} hours |

### Top Experiments

| Rank | Experiment | val_bpb | Artifact | Δ vs Baseline |
|------|-----------|---------|----------|---------------|
"""
    for i, e in enumerate(succeeded[:10]):
        m = e["metrics"]
        art = f'{m["artifact_bytes"]/1e6:.2f}MB' if m.get("artifact_bytes") else "—"
        report += f"| {i+1} | {e['name']} | {m['val_bpb']:.4f} | {art} | -{baseline - m['val_bpb']:.4f} |\n"

    report += f"""
### Improvement Timeline

| # | Experiment | val_bpb | Cumulative Improvement |
|---|-----------|---------|----------------------|
"""
    for i, e in enumerate(timeline):
        m = e["metrics"]
        report += f"| {i+1} | {e['name']} | {m['val_bpb']:.4f} | -{baseline - m['val_bpb']:.4f} |\n"

    report += f"""
### Methodology

- **Starting point:** Best merged record from Parameter Golf leaderboard
- **Protocol:** Single-variable experiments, 5-minute training budget
- **Decision rule:** KEEP if val_bpb improved AND artifact ≤ 16MB
- **Automation:** Claude Code agent (Karpathy autoresearch pattern)
- **Validation:** Fixed 50K-document FineWeb validation set

### Best Configuration

**Experiment:** {best['name']}
**val_bpb:** {best['metrics']['val_bpb']:.4f}
**Artifact:** {best['metrics'].get('artifact_bytes','?')} bytes
**Parameters:** {best['metrics'].get('total_params','?')}

---

*Generated by generate_report.py — {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""
    with open("reports/research_report.md", "w") as f:
        f.write(report)

    # PR summary
    summary = f"**{len(exps)} experiments** → best val_bpb **{best['metrics']['val_bpb']:.4f}**\n\nTop findings:\n"
    for e in succeeded[:5]:
        summary += f"- {e['name']}: {e['metrics']['val_bpb']:.4f}\n"
    with open("reports/pr_summary.md", "w") as f:
        f.write(summary)

    print(f"Report: reports/research_report.md")
    print(f"PR summary: reports/pr_summary.md")

if __name__ == "__main__": main()